pos_tweets = [('I love this car', 'pos'),
              ('This view is amazing', 'pos'),
              ('I feel great this morning', 'pos'),
              ('I am so excited about the concert', 'pos'),
              ('He is my best friend', 'pos'),
              ('This is the greatest day', 'pos'),
              ('Good market movement', 'pos'),
              ('This is going to be a bull day', 'pos'),
              ('Good growth today', 'pos'),
              ('Technology sectors are growing', 'pos'),
              ('Lots of trading today', 'pos'),
              ('The leading stocks in the market', 'pos'),
              ('This is an optimal time to enter the market', 'pos'),
              ('This is a perfect day for a bull market', 'pos'),
              ('This is prime movement for the NASDAQ', 'pos'),
              ('Apple is the foremost grower in the market', 'pos'),
              ('Two companies are finalizing a merger', 'pos'),
              ('This is disappointing day for these stocks', 'pos'),
              ('The market is trending upwards', 'pos'),
              ('There is a joint onwnership', 'pos'),
              ('Returns for these stocks are higher than expected', 'pos'),
              ('New board will do great', 'pos'),
              ('Sectors across the board are rising', 'pos'),
              ('Good international trade markets', 'pos'),
              ("China's market is booming right now", 'pos'),
              ('Stocks rose today', 'pos'),
              ('This is a true statement', 'pos'),
              ('The NASDAQ is dominating right now', 'pos'),
              ('There is a high volume of trading', 'pos'),
              ('Investors are feeling good today', 'pos'),
              ('This is a bullish market', 'pos'),
              ('It is smart to invest', 'pos'),
              ('The market is skyrocketing', 'pos'),
              ('Reported earnings', 'pos'),
              ('Investors are making and earningmoney', 'pos'),
              ('It is trending up', 'pos'),
              ('I love this sandwich.', 'pos'),
	       ('this is an amazing place!', 'pos'),
	       ('I feel very good about these beers.', 'pos'),
	       ('this is my best work.', 'pos'),
	       ("what an awesome view", 'pos'),
	       ('Lets all get rich', 'pos'),
	       ('This company is booming', 'pos'),
	       ('This invesment is attractive', 'pos')]







